---
title: "Part 2b - Evaluate whether older planes suffer more delays on a year-to-year basis"
author: "Shuayb Ibrahim"
output: pdf_document
---

```{r}
#imports
library(tidyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(stringr)
library(ggpubr)
library(cowplot)
library(gridExtra)
```

### Pre-processing

```{r}
#planes data
planes <- read.csv('dataset/plane-data.csv')
planes <- planes |> select(tailnum,issue_date) |> filter(issue_date != '' & issue_date != 'None') |>
  rename(TailNum = tailnum)
sapply(planes, function(col) sum(col=='None' | col == ''))
```

```{r}
#flights data
paths <- lapply(seq(1995,2004,1), function(year) paste0("dataset/",year,".csv"))
flights <- do.call(rbind,lapply(paths,read.csv))
flights <- flights |> select(Year,ArrDelay,TailNum) |> drop_na()
sapply(flights, function(col) sum(is.na(col)))
```

```{r}
#combined data
df <- flights |> left_join(planes,by='TailNum')
rm(flights,planes)
```

```{r}
dim(df)
summary(df)
```

```{r}
sapply(df, function(col) sum(is.na(col)))
df <- df |> drop_na()
sapply(df, function(col) sum(is.na(col)))
```

```{r}
df <- df |> mutate(issue_year = sapply(str_split(issue_date, "/"), function(x) tail(x, n = 1)), Age = Year - as.integer(issue_year)) |> filter(Age>=0) |> select(Year, Age, ArrDelay) |> group_by(Year,Age) |>
  summarise(AvgDelay = mean(ArrDelay), .groups = 'drop')
```

### Pearson's Correlation Test

```{r}
pearson <- function(x,y) {
  corr <- cor.test(x,y)
  
  r_val <- corr$estimate
  p_val <- corr$p.value
  
  return(list(r_val,p_val))
}
```

```{r}
r_vals <- c()
p_vals <- c()

for (year in 1995:2004) {
  x <- df[which(df$Year==year),]$Age
  y <- df[which(df$Year==year),]$AvgDelay
  
  test <- pearson(x,y)
  r_vals <- c(r_vals,test[[1]])
  p_vals <- c(p_vals,test[[2]])
}

names(r_vals) <- "Co-efficient"
names(p_vals) <- "P-value"
```

```{r}
rm(plot)
rm(plots)
library(patchwork)

plots <- list()
count <- 1

for (year in 1995:2004) {
  data <- df |> filter(Year == year) |> select(Age,AvgDelay) 
  plot <- ggplot(data, aes(Age,AvgDelay)) + geom_point() + geom_smooth(method = lm, formula = y ~ x) +
    labs(title = year, subtitle = paste("R-value:", sprintf("%.3f", r_vals[[count]]), " | P-value:",sprintf("%.3f", p_vals[[count]])), y="Average Delay (minutes)") + theme(axis.title.x = element_text(size = 8),
                                                  axis.title.y=element_text(size=8),
                                                  plot.title = element_text(hjust = 0.5, size = 12),
                                                  plot.subtitle = element_text(size = 5))
  plots[[length(plots)+1]] <- plot
  count <- count + 1
}

p <- plots[[1]]  + plots[[2]] +
  plots[[3]] + plots[[4]] +
  plots[[5]] + plots[[6]] +
  plots[[7]] + plots[[8]] +
  plots[[9]] + plots[[10]] + 
  plot_layout(ncol = 5,nrow = 2) + plot_annotation(title = "Do Older Planes Suffer More Delays On a Year-to-Year Basis?",
                                                    subtitle = "Between the years 1995 and 2004")
```

```{r}
p
```